name: Unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: balabala
      run: ls ${{ github.workspace }}
      
    - name: Run unit tests in Docker
      run: | 
        docker build . -t npm-tests:latest
        docker run --rm npm-tests:latest